### ISSUE TITLE
I have now Microsoft Office 2019 X64

### ISSUE THREAD

**Issue by vulliw** [HoffmannTom/outlookbackupaddin#22] opened 2018-10-07 08:31 UTC
Outlook 2016 Backup Add-In 1.7.0 no longer works with X64 !
I have installed it, not give an error message
but there is no backup in Outlook 2019 x64 (ribben)

In Outlook 2019 x32 it just works
Please help me

vulliw

**Comment by HoffmannTom** [comment] 2018-10-08 21:47
duplicate of #23

**Closed by HoffmannTom** 2018-10-08 21:47 UTC
